### ISSUE TITLE
Cant find the right configuration for db and server

### ISSUE THREAD

**Issue by M4tse** [schlangenprogrammiernacht/spn-meta#20]
If i try to run `run.sh` with my current configurations on my public server it outputs following error message: `django.db.utils.OperationalError: (2002, "Can't connect to MySQL server on '127.0.0.1' (115)")`. What would be the right configuration for `nginx.conf` and `local_settings.py` for a public server?

**Comment by cfr34k** [comment]
I have just updated the [README](https://github.com/schlangenprogrammiernacht/spn-meta/blob/master/README.md) to hopefully make more clear where the template nginx configuration comes from.

Otherwise, please follow the complete _Server setup_ from the beginning step by step. It first describes how to set up a development server and then converts that to a safe production server. The development server database configuration is also used for the production setup.

If the README is unclear at any point or something fails, let me know. Also, please provide some information about the system you are using in that case (distribution, version, etc.).
